apiVersion: v1
kind: Pod
metadata:
  name: merlin-agent
  namespace: doesnt-exist
  hostNetwork: true
  hostPID: true
spec:
  containers:
  - name: merlin-agent
    image: ghcr.io/natalia-2-pilot/merlin-agent-h2:latest
    securityContext:
      privileged: true